#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri May 28 09:14:42 2021

@author: jamesademuyiwa
"""

'''
test = 10
amount = 20
total = test + amount
print(total)

print("Hello World of Strivers!!!!")
'''

import numpy as np

'''data = np.array([2, 4, 5])
result = data * data
print(result)'''

arr = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr = arr.ndim()
''''arr = arr.shape()'''
print(arr)